### PR TITLE
[WIP] Implementing the final bastin's scheme for trust region radius

### PR DESCRIPTION
**Pull request by yash2798**

### CODE REVIEW

**Comment by yash2798** [comment]
@ChrisRackauckas for the convergence tests, I am thinking to test the value $ ||u_{k+1} - u_k $ to be smaller than a given tolerance and if it is, the test passes. Is this fine?

Also some time back, you pointed out to involve `NLSolve.jl` in the convergence tests. what do you exactly mean by that?

**Comment by ChrisRackauckas** [comment]
yes

> Also some time back, you pointed out to involve NLSolve.jl in the convergence tests. what do you exactly mean by that?

https://github.com/SciML/SciMLNLSolve.jl

**Comment by yash2798** [comment]
@ChrisRackauckas This is ready to be merged, the issues are resolved and tests pass. i'll continue adding convergence tests in a separate pr.

**Comment by ChrisRackauckas** [comment]
resolve conflicts

**Comment by ChrisRackauckas** [comment]
looks like it just needs a formatter run

**Comment by yash2798** [comment]
Do you mean just run the command as given [here](https://github.com/SciML/SciMLStyle#juliaformatter)

**Comment by yash2798** [comment]
@ChrisRackauckas I did format and resolved conflicts but still some CI checks fail. why is that happening?

**Comment by yash2798** [comment]
This pr got messed up a little so i am closing it. Here is the [new one](https://github.com/SciML/NonlinearSolve.jl/pull/191)

**Pull request closed without merging**
