### PR TITLE
Add documentation

### PR DESCRIPTION
**Pull request by ChrisRackauckas**
Requires the move to SciML to work.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
@mkg33 take a look?

**Comment by mkg33** [comment]
Is it just a matter of moving this repository to SciML/ ?

**Comment by ChrisRackauckas** [comment]
To make it build? Yes. I wanted you to look at the actual docs though.

**Comment by mkg33** [comment]
Haha, OK. I was just thinking: how am I supposed to move it if I don't have the admin rights.

**Pull request merged**
