### PR TITLE
Use DI preparation result when initializing Jacobian

### LINKED ISSUE #469: cache construction is no longer type stable
I will generate a MWE but the DI extras is not type stable, atleast in the bruss case I tested.

### PR DESCRIPTION
**Pull request by gdalle**
This should fix #469 for the example you gave.

### CODE REVIEW

**Review by avik-pal — APPROVED** [review]
Ah my bad, completely missed it. Thanks!

**Comment by gdalle** [comment]
It would be fair to expect `DI.jacobian(b, AutoForwardDiff(; chunksize=2), x)` to be type-stable. The problem is that this falls back directly onto `ForwardDiff.jacobian(f, x)`, which is itself type-unstable since I don't give it the static `Chunk` size it needs to create the `JacobianConfig`. I could give it the chunk size, but I would have to create a `JacobianConfig` myself for that, which is unnecessary work e.g. [for StaticArrays](https://github.com/JuliaDiff/ForwardDiff.jl/blob/ec74fbc32b10bbf60b3c527d8961666310733728/ext/ForwardDiffStaticArraysExt.jl#L66).

**Comment by ChrisRackauckas** [comment]
We allowed for specifying chunk size as a Val to handle that. We probably need to ensure that's allowed in ADTypes implementations.

**Comment by gdalle** [comment]
This should solve it: https://github.com/gdalle/DifferentiationInterface.jl/pull/541

**Pull request merged**
