### PR TITLE
Trust Region - Fan's method

### PR DESCRIPTION
**Pull request by yash2798**

### CODE REVIEW

**Comment by yash2798** [comment]
Hi @ChrisRackauckas , line 307 and 309, is it alright if I calculate jacobian through direct `ForwardDiff.jacobian` calls? If Hei's scheme is used they'll be calculated only once in the cache `init` function

**Comment by yash2798** [comment]
nvm i think jvp will work here too.

**Comment by yash2798** [comment]
@ChrisRackauckas  if this seems alright, this can be merged.

**Comment by ChrisRackauckas** [comment]
Next step, can we get a test that like 4 iterations of in-place and out-of-place match results?

**Comment by yash2798** [comment]
> Next step, can we get a test that like 4 iterations of in-place and out-of-place match results?

Sure I will make a pr for this soon.

**Pull request merged**
