### PR TITLE
Consolidate Stats Handling

### LINKED ISSUE #410: Consolidate `stats` handling
As pointed out by @oscardssmith, it would be good to store a centralized stats in the cache and update references to it instead of adding up the stats at the end.

Would probably make https://github.com/SciML/OrdinaryDiffEq.jl/pull/2167 easier

### PR DESCRIPTION
**Pull request by avik-pal**
Fixes #410

Oops lost my local changes it seems...

Merge after https://github.com/SciML/NonlinearSolve.jl/pull/435

### CODE REVIEW

**Comment by avik-pal** [comment]
Now `cache.stats` gives the total counts correctly. For polyalgorithms this means we get the accumulated stats from all the solve calls.

**Comment by avik-pal** [comment]
cc @oscardssmith because you needed this in OrdinaryDiffEq.

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by avik-pal** [comment]
Can you do it? I am not sure what broke, this was a purely internal API change

**Comment by oscardssmith** [comment]
will do. The problem was that OrdinaryDiffEq with NonlinearSolveAlg runs the `step!(cache)` loops of a nonlinear solver itself and was using `nf` to determine how many calls the `step!` had made to update the integrator's stats.

**Pull request merged**
