### PR TITLE
Use a proper polyalgorithm algorithm type

### PR DESCRIPTION
**Pull request by avik-pal**
Adding this since it makes it easy to write type-stable polyalgorithms. Once this is in we can simply define a custom polyalgorithm algorithm for https://github.com/SciML/NonlinearSolve.jl/pull/277 as well.

### CODE REVIEW

**Review by ChrisRackauckas — APPROVED** [review]

**Comment by avik-pal** [comment]
I thing that might break is if someone was writing `::RobustMultiNewton`. Do we guarantee that the algorithms are types that can be dispatched on?

**Comment by ChrisRackauckas** [comment]
no

**Comment by avik-pal** [comment]
@ChrisRackauckas  is the forwarddiff linear solve failure from nonlinear solve or something changed in linear solve?

**Comment by ChrisRackauckas** [comment]
That's a LinearSolve thing, don't worry about it.

**Comment by ChrisRackauckas** [comment]
Can you make the 23 tests more robust?

**Comment by avik-pal** [comment]
Probably disable the `GeneralBroyden`? It fails only sometimes on CI and locally always passes. I can't even reproduce the failure reliably

**Comment by ChrisRackauckas** [comment]
Or make it simpler, like number of successes > 5

**Pull request merged**
