### PR TITLE
use LinearSolve precs setup

### PR DESCRIPTION
**Pull request by oscardssmith**
This updates NonlinearSolve to use the new `precs` interface in LinearSolve.

### CODE REVIEW

**Comment by avik-pal** [comment]
This would require a major version bump.

**Comment by mpf** [comment]
See also this Julia Discourse [post](https://discourse.julialang.org/t/warning-when-using-nonlinearsolve-jl-with-linearsolve-jl-and-minres/119781?u=mpf01).

**Comment by ChrisRackauckas** [comment]
Is this needed?

**Comment by oscardssmith** [comment]
it's not needed, but will be nice (as it will bring the interface inline with LinearSolve and OrdinaryDiffEq@V7

**Comment by ChrisRackauckas** [comment]
okay, I thought it was covered by another PR already.

**Comment by oscardssmith** [comment]
https://github.com/SciML/NonlinearSolve.jl/pull/465 was a simpler fix that fixed the bug that led me to create this PR, but all that did was switch NonlinearSolve from a cursed diagonal preconditioner to a real diagonal preconditioner, whereas this PR removes the preconditioner from the NonlinearSolve side entirely since the LinearSolve side can do all the work.

**Comment by oscardssmith** [comment]
@avik-pal if I rebase this, do you think we're ready to do the version bump required? I think this is a good change, but I don't really want to go through the rebase until you think we're conceptually ready to merge.

**Comment by avik-pal** [comment]
not yet, we need https://github.com/SciML/NonlinearSolve.jl/pull/458 to be merged before doing a bump

**Comment by avik-pal** [comment]
@oscardssmith we can get this in now

**Pull request closed without merging**
